# Generated by Django 4.2 on 2023-04-20 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoretracker', '0003_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoretracker.course'),
        ),
        migrations.AlterField(
            model_name='round',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
