# Generated by Django 4.2 on 2023-04-20 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoretracker', '0004_alter_round_course_alter_round_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField(null=True)),
                ('swings', models.IntegerField(null=True)),
                ('putts', models.IntegerField(null=True)),
                ('hole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoretracker.hole')),
                ('hole_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoretracker.round')),
            ],
        ),
    ]
