# Generated by Django 4.2 on 2023-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoretracker', '0005_holescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hole',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hole',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
